name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '10'
      - run: sudo npm install -g vsce
      - run: npm install
      - run: npm run compile
      - run: vsce package
