name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@1
        with:
          java-version: 11

      - name: Build VSCode extension
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: sudo npm install -g vsce
      - run: npm install
      - run: npm run compile
      - run: vsce package
